"""KiCad schematic generation (flat and hierarchical)."""

from kicad.utils import _uuid
from kicad.symbol import PIN_PITCH, FONT_SYM, FONT_REF
from kicad.common import (
    GRID_X, ORIGIN_X,
    _place_modules, _emit_lib_symbols, _emit_symbol_instance, _emit_net_labels,
)


def generate_flat_schematic(top_mod, sub_modules, lib_prefix="half_cpu"):
    """Generate a flat .kicad_sch with all submodules on one sheet."""
    seen = set()
    unique_subs = []
    for inst in top_mod.instances:
        if inst.module_name not in seen:
            seen.add(inst.module_name)
            for m in sub_modules:
                if m.name == inst.module_name:
                    unique_subs.append(m)
                    break

    positions = _place_modules(unique_subs)

    lines = [
        '(kicad_sch',
        '  (version 20231120)',
        '  (generator "verilog_export")',
        '  (generator_version "1.0")',
        f'  (uuid "{_uuid()}")',
        '',
        '  (paper "A1")',
        '',
        '  (title_block',
        f'    (title "{top_mod.name} — Flat Architecture")',
        '    (comment 1 "Auto-generated by verilog_export")',
        '  )',
        '',
        _emit_lib_symbols(unique_subs, lib_prefix),
        '',
    ]

    for i, mod in enumerate(unique_subs, 1):
        pos = positions[mod.name]
        lines.append(_emit_symbol_instance(mod, pos, i, lib_prefix))
        lines.append('')

    lines.append('')
    lines.append(_emit_net_labels(top_mod, unique_subs, positions, lib_prefix))
    lines.append('')

    total_w = len(unique_subs) * GRID_X
    cx = ORIGIN_X + total_w / 2
    lines.append(f'  (text "{top_mod.name}" (at {cx:.2f} 25.4 0) (effects (font (size 5.08 5.08) bold)))')
    lines.append('')

    lines.append(')')
    return "\n".join(lines)


def generate_hier_schematic(top_mod, sub_modules, registry, lib_prefix="half_cpu"):
    """Generate a hierarchical schematic: root + per-category sub-sheets."""

    categories = {}
    mod_map = {m.name: m for m in sub_modules}
    inst_mod_names = [inst.module_name for inst in top_mod.instances]

    for mname in inst_mod_names:
        if mname not in mod_map or mname not in registry:
            continue
        mod_path = registry[mname]["path"]
        rel = mod_path.split("/modules/")[-1] if "/modules/" in mod_path else mod_path
        parts = rel.split("/")
        if len(parts) >= 2:
            cat = parts[0]
            if parts[0] == "lib" and len(parts) >= 3:
                cat = f"lib/{parts[1]}"
            elif parts[0] in ("subsystem", "integration"):
                cat = parts[0]
        else:
            cat = "other"
        categories.setdefault(cat, [])
        m = mod_map[mname]
        if m not in categories[cat]:
            categories[cat].append(m)

    sheets = {}
    sheet_info = []

    for cat, mods in sorted(categories.items()):
        sheet_name = cat.replace("/", "_").upper()
        fname = f"{cat.replace('/', '_')}.kicad_sch"
        positions = _place_modules(mods)

        h_labels_in = set()
        h_labels_out = set()
        for inst in top_mod.instances:
            if inst.module_name not in [m.name for m in mods]:
                continue
            sub = mod_map.get(inst.module_name)
            if not sub:
                continue
            port_map = {p.name: p for p in sub.ports}
            for pname, net in inst.connections.items():
                p = port_map.get(pname)
                if not p:
                    continue
                net_clean = net.strip()
                if p.direction == "input":
                    h_labels_in.add(net_clean)
                else:
                    h_labels_out.add(net_clean)

        slines = [
            '(kicad_sch',
            '  (version 20231120)',
            '  (generator "verilog_export")',
            '  (generator_version "1.0")',
            f'  (uuid "{_uuid()}")',
            '  (paper "A3")',
            '  (title_block',
            f'    (title "{top_mod.name} — {sheet_name}")',
            '    (comment 1 "Auto-generated sub-sheet")',
            '  )',
            '',
            _emit_lib_symbols(mods, lib_prefix),
            '',
        ]

        hy = 40.64
        for net in sorted(h_labels_in):
            slines.append(f'  (hierarchical_label "{net}" (shape input) (at 25.4 {hy:.2f} 180) (effects (font (size {FONT_REF} {FONT_REF}))) (uuid "{_uuid()}"))')
            hy += 2.54
        for net in sorted(h_labels_out):
            slines.append(f'  (hierarchical_label "{net}" (shape output) (at 355.6 {hy:.2f} 0) (effects (font (size {FONT_REF} {FONT_REF}))) (uuid "{_uuid()}"))')
            hy += 2.54
        slines.append('')

        for i, mod in enumerate(mods, 1):
            pos = positions[mod.name]
            slines.append(_emit_symbol_instance(mod, pos, i, lib_prefix))
            slines.append('')

        slines.append(_emit_net_labels(top_mod, mods, positions, lib_prefix))
        slines.append('')
        slines.append(f'  (text "{sheet_name}" (at 190.5 25.4 0) (effects (font (size 3.81 3.81) bold)))')
        slines.append(')')

        sheets[fname] = "\n".join(slines)
        sheet_info.append((sheet_name, fname, sorted(h_labels_in), sorted(h_labels_out)))

    # Root sheet
    rlines = [
        '(kicad_sch',
        '  (version 20231120)',
        '  (generator "verilog_export")',
        '  (generator_version "1.0")',
        f'  (uuid "{_uuid()}")',
        '  (paper "A2")',
        '  (title_block',
        f'    (title "{top_mod.name} — Hierarchical Top")',
        '    (comment 1 "Auto-generated by verilog_export")',
        '  )',
        '  (lib_symbols)',
        '',
    ]

    sx = 50.8
    for sname, sfname, h_in, h_out in sheet_info:
        n_pins = len(h_in) + len(h_out)
        sh_height = max(25.4, (n_pins + 2) * PIN_PITCH)
        sh_width = 76.2

        rlines.append(f'  (sheet')
        rlines.append(f'    (at {sx:.2f} 50.8) (size {sh_width:.2f} {sh_height:.2f})')
        rlines.append(f'    (stroke (width 0.254) (type solid))')
        rlines.append(f'    (fill (type background))')
        rlines.append(f'    (uuid "{_uuid()}")')
        rlines.append(f'    (property "Sheetname" "{sname}" (at {sx:.2f} 48.26 0) (effects (font (size 2.54 2.54) bold)))')
        rlines.append(f'    (property "Sheetfile" "{sfname}" (at {sx:.2f} {50.8 + sh_height + 1.27:.2f} 0) (effects (font (size {FONT_REF} {FONT_REF})) hide))')

        py = 55.88
        for net in h_in:
            rlines.append(f'    (pin "{net}" input (at {sx:.2f} {py:.2f} 180) (effects (font (size {FONT_SYM} {FONT_SYM}))) (uuid "{_uuid()}"))')
            py += PIN_PITCH
        for net in h_out:
            rlines.append(f'    (pin "{net}" output (at {sx + sh_width:.2f} {py:.2f} 0) (effects (font (size {FONT_SYM} {FONT_SYM}))) (uuid "{_uuid()}"))')
            py += PIN_PITCH

        rlines.append(f'  )')
        rlines.append('')
        sx += sh_width + 25.4

    cx = sx / 2
    rlines.append(f'  (text "{top_mod.name} — Hierarchical Architecture" (at {cx:.2f} 25.4 0) (effects (font (size 5.08 5.08) bold)))')
    rlines.append('')

    rlines.append('')
    ey = 160.02
    for p in top_mod.ports:
        shape = "input" if p.direction == "input" else "output"
        rlines.append(f'  (global_label "{p.label()}" (shape {shape}) (at 25.4 {ey:.2f} 0)')
        rlines.append(f'    (effects (font (size {FONT_REF} {FONT_REF}))) (uuid "{_uuid()}")')
        rlines.append(f'    (property "Intersheetref" "" (at 0 0 0) (effects (font (size {FONT_REF} {FONT_REF})) hide)))')
        ey += 5.08

    rlines.append('')
    rlines.append(')')

    root_name = f"{top_mod.name}_hier.kicad_sch"
    sheets[root_name] = "\n".join(rlines)

    return sheets
