SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src

SIM_BUILD = sim_build/dff
VERILOG_SOURCES += $(SRC_DIR)/dff.v
VERILOG_SOURCES += $(PWD)/tb_dff.v
COMPILE_ARGS += -I$(SRC_DIR)

TOPLEVEL = tb_dff
COCOTB_TEST_MODULES = test_dff

include $(shell cocotb-config --makefiles)/Makefile.sim
